- block:
  - name: set_fact > combine default and custom mkinitcpio config
    set_fact:
      mkinitcpio_combined: "{{ _mkinitcpio_config | combine(mkinitcpio_config) }}"

  - name: template > generate mkinitcpio config
    template:
      src:  mkinitcpio.conf
      dest: /etc/mkinitcpio.conf
      mode: "0644"
    notify: "handlers | shell > generate initial RAM disk"

  - import_tasks: preset.yml

  # - name: shell > force creation of initial ramdisk
  #   shell:
  #     cmd: /bin/true
  #   notify: "(handlers) shell > generate initial RAM disk"
  #   when: mkinitcpio_force_create

  - name: meta > run handlers before modifying initramfs.img permissions
    meta: flush_handlers

  ## KO: can't be apply
  - name: file > restrict access permissions to initramfs
    file:
      path: "/boot/{{ item }}"
      mode: "0600"
    with_items:
      - initramfs-linux.img
      - initramfs-linux-fallback.img

  become_user: root
  tags: initrd
